# Generated by Django 3.1.4 on 2020-12-20 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_remove_player_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('black', models.FileField(blank=True, null=True, upload_to='')),
                ('blue', models.FileField(blank=True, null=True, upload_to='')),
                ('grey', models.FileField(blank=True, null=True, upload_to='')),
                ('green', models.FileField(blank=True, null=True, upload_to='')),
                ('light_blue', models.FileField(blank=True, null=True, upload_to='')),
                ('light_green', models.FileField(blank=True, null=True, upload_to='')),
                ('magenta', models.FileField(blank=True, null=True, upload_to='')),
                ('orange', models.FileField(blank=True, null=True, upload_to='')),
                ('pink', models.FileField(blank=True, null=True, upload_to='')),
                ('purple', models.FileField(blank=True, null=True, upload_to='')),
                ('red', models.FileField(blank=True, null=True, upload_to='')),
                ('white', models.FileField(blank=True, null=True, upload_to='')),
                ('yellow', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
