# Generated by Django 3.1.4 on 2020-12-20 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='grey',
            new_name='gray',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='light_blue',
            new_name='greenyellow',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='light_green',
            new_name='skyblue',
        ),
    ]
