# Generated by Django 3.1.4 on 2021-01-16 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20201224_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='previous_record',
        ),
    ]
